import React, { createContext, useContext, useState, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  es: {
    'nav.home': 'Inicio',
    'nav.login': 'Iniciar Sesión',
    'nav.register': 'Registrarse',
    'nav.dashboard': 'Panel',
    'nav.files': 'Archivos',
    'nav.admin': 'Administrador',
    'nav.logout': 'Cerrar Sesión',
    'home.title': 'Apoya Nuestra Misión',
    'home.subtitle': 'Haz una donación y obtén acceso a contenido premium exclusivo',
    'home.donateButton': 'Hacer Donación',
    'home.loginPrompt': '¿Ya tienes una cuenta?',
    'home.loginLink': 'Inicia sesión aquí',
    'home.whyDonate': '¿Por qué donar?',
    'home.exclusiveDocuments': 'Documentos Exclusivos',
    'home.exclusiveDocumentsDesc': 'Accede a documentos PDF premium y materiales de investigación',
    'home.videoContent': 'Contenido de Video',
    'home.videoContentDesc': 'Mira videos educativos exclusivos y tutoriales',
    'home.downloadAccess': 'Acceso de Descarga',
    'home.downloadAccessDesc': 'Descarga archivos para acceso sin conexión',
    'home.pleaseRegisterLogin': 'Por favor regístrate o inicia sesión para hacer una donación',
    'login.title': 'Iniciar Sesión',
    'login.email': 'Correo Electrónico',
    'login.password': 'Contraseña',
    'login.button': 'Iniciar Sesión',
    'login.registerPrompt': '¿No tienes una cuenta?',
    'login.registerLink': 'Regístrate aquí',
    'login.failed': 'Error al iniciar sesión',
    'login.failedDesc': 'Correo electrónico o contraseña inválidos.',
    'register.title': 'Registrarse',
    'register.firstName': 'Nombre',
    'register.lastName': 'Apellido',
    'register.email': 'Correo Electrónico',
    'register.password': 'Contraseña',
    'register.language': 'Idioma',
    'register.button': 'Registrarse',
    'register.loginPrompt': '¿Ya tienes una cuenta?',
    'register.loginLink': 'Inicia sesión aquí',
    'dashboard.title': 'Panel',
    'dashboard.profile': 'Perfil',
    'dashboard.totalDonated': 'Total Donado',
    'dashboard.editProfile': 'Editar Perfil',
    'files.title': 'Archivos Premium',
    'files.folders': 'Carpetas',
    'files.noAccess': 'Sin acceso - Requiere donación mínima de',
    'files.hasAccess': 'Acceso concedido',
    'files.download': 'Descargar',
    'files.backToFolders': '← Volver a Carpetas',
    'files.filesIn': 'Archivos en',
    'files.noFilesYet': 'Aún no hay archivos en esta carpeta.',
    'files.pleaseLogin': 'Por favor inicia sesión para acceder a los archivos',
    'files.loading': 'Cargando...',
    'files.type': 'Tipo:',
    'files.size': 'Tamaño:',
    'admin.title': 'Panel de Administración',
    'admin.users': 'Usuarios',
    'admin.totalUsers': 'Total de Usuarios',
    'admin.viewDetails': 'Ver Detalles',
    'admin.totalDonations': 'Total de Donaciones',
    'admin.uploadFile': 'Subir Archivo',
    'admin.folder': 'Carpeta',
    'admin.file': 'Archivo',
    'admin.upload': 'Subir',
    'admin.general': 'General',
    'admin.premium': 'Premium',
    'admin.userDetails': 'Detalles del Usuario',
    'admin.profile': 'Perfil',
    'admin.name': 'Nombre:',
    'admin.email': 'Correo:',
    'admin.language': 'Idioma:',
    'admin.totalDonated': 'Total Donado:',
    'admin.recentDonations': 'Donaciones Recientes',
    'admin.folderAccess': 'Acceso a Carpetas',
    'admin.donated': 'donado',
    'admin.donations': 'donaciones',
    'admin.admin': 'Administrador',
    'admin.accessDenied': 'Acceso denegado. Se requieren privilegios de administrador.',
    'donation.title': 'Hacer una Donación',
    'donation.amount': 'Cantidad (USD)',
    'donation.minAmount': 'Mínimo: $5',
    'donation.maxAmount': 'Máximo: $1000',
    'donation.cardDetails': 'Detalles de Tarjeta',
    'donation.donate': 'Donar',
    'donation.processing': 'Procesando...',
    'language.english': 'English',
    'language.spanish': 'Español',
    'common.loading': 'Cargando...',
    'common.email': 'Correo:',
    'common.name': 'Nombre:',
    'common.language': 'Idioma:',
  },
  en: {
    'nav.home': 'Home',
    'nav.login': 'Login',
    'nav.register': 'Register',
    'nav.dashboard': 'Dashboard',
    'nav.files': 'Files',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    'home.title': 'Support Our Mission',
    'home.subtitle': 'Make a donation and get access to exclusive premium content',
    'home.donateButton': 'Make a Donation',
    'home.loginPrompt': 'Already have an account?',
    'home.loginLink': 'Login here',
    'home.whyDonate': 'Why Donate?',
    'home.exclusiveDocuments': 'Exclusive Documents',
    'home.exclusiveDocumentsDesc': 'Access premium PDF documents and research materials',
    'home.videoContent': 'Video Content',
    'home.videoContentDesc': 'Watch exclusive educational videos and tutorials',
    'home.downloadAccess': 'Download Access',
    'home.downloadAccessDesc': 'Download files for offline access',
    'home.pleaseRegisterLogin': 'Please register or login to make a donation',
    'login.title': 'Login',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.button': 'Login',
    'login.registerPrompt': "Don't have an account?",
    'login.registerLink': 'Register here',
    'login.failed': 'Login failed',
    'login.failedDesc': 'Invalid email or password.',
    'register.title': 'Register',
    'register.firstName': 'First Name',
    'register.lastName': 'Last Name',
    'register.email': 'Email',
    'register.password': 'Password',
    'register.language': 'Language',
    'register.button': 'Register',
    'register.loginPrompt': 'Already have an account?',
    'register.loginLink': 'Login here',
    'dashboard.title': 'Dashboard',
    'dashboard.profile': 'Profile',
    'dashboard.totalDonated': 'Total Donated',
    'dashboard.editProfile': 'Edit Profile',
    'files.title': 'Premium Files',
    'files.folders': 'Folders',
    'files.noAccess': 'No access - Requires minimum donation of',
    'files.hasAccess': 'Access granted',
    'files.download': 'Download',
    'files.backToFolders': '← Back to Folders',
    'files.filesIn': 'Files in',
    'files.noFilesYet': 'No files in this folder yet.',
    'files.pleaseLogin': 'Please login to access files',
    'files.loading': 'Loading...',
    'files.type': 'Type:',
    'files.size': 'Size:',
    'admin.title': 'Admin Panel',
    'admin.users': 'Users',
    'admin.totalUsers': 'Total Users',
    'admin.viewDetails': 'View Details',
    'admin.totalDonations': 'Total Donations',
    'admin.uploadFile': 'Upload File',
    'admin.folder': 'Folder',
    'admin.file': 'File',
    'admin.upload': 'Upload',
    'admin.general': 'General',
    'admin.premium': 'Premium',
    'admin.userDetails': 'User Details',
    'admin.profile': 'Profile',
    'admin.name': 'Name:',
    'admin.email': 'Email:',
    'admin.language': 'Language:',
    'admin.totalDonated': 'Total Donated:',
    'admin.recentDonations': 'Recent Donations',
    'admin.folderAccess': 'Folder Access',
    'admin.donated': 'donated',
    'admin.donations': 'donations',
    'admin.admin': 'Admin',
    'admin.accessDenied': 'Access denied. Admin privileges required.',
    'donation.title': 'Make a Donation',
    'donation.amount': 'Amount (USD)',
    'donation.minAmount': 'Minimum: $5',
    'donation.maxAmount': 'Maximum: $1000',
    'donation.cardDetails': 'Card Details',
    'donation.donate': 'Donate',
    'donation.processing': 'Processing...',
    'language.english': 'English',
    'language.spanish': 'Español',
    'common.loading': 'Loading...',
    'common.email': 'Email:',
    'common.name': 'Name:',
    'common.language': 'Language:',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState('es');

  const t = (key: string): string => {
    return translations[language as keyof typeof translations]?.[key as keyof typeof translations.es] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
